# Промежуток времени, за который ожидаются фото последнего сообщения (сек). Увеличить, если не все фото пересылаются.
latency = 0.05

# Соответствие предметов (в выпадающем меню) чатам (названиям). Название должно быть на момент добавления бота в чат.
[[subjects]]
subject = "Биология"
chat = "Сириус (бот) биология"

[[subjects]]
subject = "Химия"
chat = "Сириус (бот) химия"

[[subjects]]
subject = "Математика"
chat = "Сириус (бот) математика"

[[subjects]]
subject = "Информатика"
chat = "Сириус (бот) информатика"

[[subjects]]
subject = "Физика"
chat = "Сириус (бот) физика"
